# Generated by Django 4.1.2 on 2022-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='default_profilepic.jpg', upload_to='profile_photos'),
        ),
    ]
