# Generated by Django 4.1.2 on 2022-10-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='default.profilepic.jpg', upload_to='profile_photos'),
        ),
    ]
